# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "e9fa874ffa470da747420f23c2ea4f03"
name = "24-04-19-test-remote-dom"
handle = "24-04-19-test-remote-dom"
application_url = "https://bow-wars-administration-universal.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-plus-shop.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://bow-wars-administration-universal.trycloudflare.com/auth/callback",
  "https://bow-wars-administration-universal.trycloudflare.com/auth/shopify/callback",
  "https://bow-wars-administration-universal.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
